name: Remote API proxy
version: 1.3.0
slug: remote_api_soluno
description: Remote API proxy for Home Assistant with watchdog
url: https://developers.home-assistant.io/docs/supervisor/development/#supervisor-api-access
arch:
- armhf
- armv7
- aarch64
- amd64
- i386
startup: application
advanced: true
stage: experimental
boot: auto
hassio_api: true
hassio_role: admin
ports:
  80/tcp: 80
options: {}
schema: false
image: homeassistant/{arch}-addon-dev-remote_api
init: false
